### ISSUE TITLE
Proposed Analysis: gender distribution

### ISSUE THREAD

**Issue by rjcorb** [rokitalab/pbta-genetic-ancestry#3]
#### What are the scientific goals of the analysis?

Plot gender distribution across PBTA tumor histology patient groups, and assess if any histologies exhibit a gender bias. 

#### What methods do you plan to use to accomplish the scientific goals?

Use the `plot_enr` function from `analyses/add-histologies/util/heatmap_function.R`

#### What input data are required for this analysis?

[merged_ancestry_histology_data.tsv ](https://github.com/rokitalab/pbta-genetic-ancestry/blob/main/analyses/add-histologies/results/merged_ancestry_histology_data.tsv)

#### How long do you expect is needed to complete the analysis? Will it be a multi-step 
analysis?

1 day

#### Who will complete the analysis (please add a GitHub handle here if relevant)?

@rjcorb

**Comment by jharenza** [comment]
closing, as was from workshop demo
